services:
  presto-coordinator:
    image: prestodb/presto:latest
    container_name: presto-coordinator
    hostname: presto-coordinator
    ports:
      - "8080:8080"
    environment:
      - CATALOG_MANAGEMENT=dynamic
    volumes:
      - ./presto-coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./presto-coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto-coordinator/log.properties:/opt/presto-server/etc/log.properties
      - ./presto-coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./datasources/catalog:/opt/presto-server/etc/catalog
    networks:
      presto:
        ipv4_address: 10.18.0.8


  presto-worker1:
    image: prestodb/presto:latest
    container_name: presto-worker1
    hostname: presto-worker1
    volumes:
      - ./presto-workers/node.properties:/opt/presto-server/etc/node.properties
      - ./presto-workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto-workers/log.properties:/opt/presto-server/etc/log.properties
      - ./presto-workers/config.properties:/opt/presto-server/etc/config.properties
      - ./datasources/catalog:/opt/presto-server/etc/catalog
    networks:
      presto:
        ipv4_address: 10.18.0.18

  
  presto-worker2:
    image: prestodb/presto:latest
    container_name: presto-worker2
    hostname: presto-worker2
    volumes:
      - ./presto-workers/node.properties:/opt/presto-server/etc/node.properties
      - ./presto-workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto-workers/log.properties:/opt/presto-server/etc/log.properties
      - ./presto-workers/config.properties:/opt/presto-server/etc/config.properties
      - ./datasources/catalog:/opt/presto-server/etc/catalog
    networks:
      presto:
        ipv4_address: 10.18.0.28
  
  
  presto-worker3:
    image: prestodb/presto:latest
    container_name: presto-worker3
    hostname: presto-worker3
    volumes:
      - ./presto-workers/node.properties:/opt/presto-server/etc/node.properties
      - ./presto-workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto-workers/log.properties:/opt/presto-server/etc/log.properties
      - ./presto-workers/config.properties:/opt/presto-server/etc/config.properties
      - ./datasources/catalog:/opt/presto-server/etc/catalog
    networks:
      presto:
        ipv4_address: 10.18.0.38
  
  
  presto-worker4:
    image: prestodb/presto:latest
    container_name: presto-worker4
    hostname: presto-worker4
    volumes:
      - ./presto-workers/node.properties:/opt/presto-server/etc/node.properties
      - ./presto-workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto-workers/log.properties:/opt/presto-server/etc/log.properties
      - ./presto-workers/config.properties:/opt/presto-server/etc/config.properties
      - ./datasources/catalog:/opt/presto-server/etc/catalog
    networks:
      presto:
        ipv4_address: 10.18.0.48
  

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./datasources/db_population_scripts/mongo_populate.sh:/docker-entrypoint-initdb.d/mongo_populate.sh
      - ./data/csv_data:/mongo_data
      - mongo_data:/data/db
    networks:
      presto:
        ipv4_address: 10.18.0.108


  cassandra:
    image: cassandra:5.0.2-jammy
    container_name: cassandra
    hostname: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME="test"
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=true
      - CASSANDRA_USERNAME=root
      - CASSANDRA_PASSWORD=root
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra 
      - ./data/csv_data:/data
      - ./datasources/db_population_scripts/cassandra_populate.cql:/cassandra_populate.cql
    healthcheck:
      test: ["CMD", "cqlsh", "-u root", "-p root", "-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      presto:
        ipv4_address: 10.18.0.118


  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:5.0.2-jammy
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./datasources/db_population_scripts/cassandra_populate.cql:/cassandra_populate.cql
      - ./data/csv_data:/data
    command: /bin/bash -c "echo Loading cassandra keyspace && cqlsh 10.18.0.118 -f /cassandra_populate.cql"
    networks:
      presto:
        ipv4_address: 10.18.0.119


  postgres: 
    image: postgres:17.0
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=adis
    ports:
      - "5432:5432"
    volumes:
      - ./datasources/db_population_scripts/postgres_populate.sql:/docker-entrypoint-initdb.d/postgres_populate.sql
      - postgres_data:/var/lib/postgresql/data
      - ./data/csv_data:/data
    networks:
      presto:
        ipv4_address: 10.18.0.128


networks:
  presto:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/24
          gateway: 10.18.0.1

volumes:
  postgres_data:
    name: postgres_data
  mongo_data:
    name: mongo_data
  cassandra_data:
    name: cassandra_data
