version: "3.9"
services:
  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra
  #   hostname: cassandra
  #   ports:
  #     - "9042:9042"
  
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   hostname: postgres
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTFRES_DB: test
  #   ports:
  #     - "5432:5432"

networks:
  default:
    driver: bridge
