select count(*) from mongodb.adis.customer;
select count(*) from mongodb.adis.customer_address;
select count(*) from mongodb.adis.household_demographics;
select count(*) from mongodb.adis.income_band;
select count(*) from mongodb.adis.promotion;
select count(*) from mongodb.adis.web_page; 
select count(*) from mongodb.adis.call_center; 
select count(*) from mongodb.adis.dbgen_version; 
select count(*) from mongodb.adis.catalog_page; 
